# Generated by Django 4.1.3 on 2023-04-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="studinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sname", models.CharField(max_length=100)),
                ("mail", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=400)),
                ("phone", models.IntegerField()),
            ],
        ),
    ]
